### ISSUE TITLE
Creation of custom resource fails with:  __init__() got an unexpected keyword argument 'typeConfiguration' (TypeError)

### ISSUE THREAD

**Issue by yiuc** [aws-cloudformation/cloudformation-cli-python-plugin#140]
It seems to have been happening since I upgraded cloudformation-cli-python-lib to 2.1.4

When I am deleting a resource using my custom resource provider, I get this error: `__init__() got an unexpected keyword argument 'typeConfiguration' (TypeError)`

I was running into the same issue as [136](https://github.com/aws-cloudformation/cloudformation-cli-python-plugin/issues/136) so I updated the library, as recommended in that issue. I get this instead, and I can't find any information about it online.

![image](https://user-images.githubusercontent.com/5475929/100060751-f319de00-2e67-11eb-883e-b8adfc699695.png)

**Comment by ArnoldKell** [comment]
I am running into the same issue. Initially the update fixed the issue in #136 for us (I made that issue) and it was working for a bit after that, however today creation of the resource started failing today again (or at least we only noticed it today, the last time I remember it working was on Friday).

**Comment by jaymccon** [comment]
It was my understanding that #125 should have prevented this from happening, but clearly there is another place that needs a similar patch
