### ISSUE TITLE
Creation of custom resource fails with: __init__() got an unexpected keyword argument 'previousSystemTags' (TypeError)

### ISSUE THREAD

**Issue by ArnoldKell** [aws-cloudformation/cloudformation-cli-python-plugin#136]
My custom resource provider (which has been working great for the past couple of months) seems have a problem which I can't quite put my finger on. It seems to have been happening since I upgraded cloudformation-cli-python-lib from 2.1.0 to 2.1.3.

When I am creating a resource using my custom resource provider, I get this error: `__init__() got an unexpected keyword argument 'previousSystemTags' (TypeError)`

I was running into the same issue as #130 so I updated the library, as recommended in that issue. I got rid of my original issue, but now I get this instead and I can't find any information about it online.

**Comment by ammokhov** [comment]
could you try changing `requirements.txt` to [2.1.3](https://github.com/aws-cloudformation/cloudformation-cli-python-plugin/blob/master/python/rpdk/python/templates/requirements.txt#L1)?

**Comment by ArnoldKell** [comment]
> could you try changing `requirements.txt` to [2.1.3](https://github.com/aws-cloudformation/cloudformation-cli-python-plugin/blob/master/python/rpdk/python/templates/requirements.txt#L1)?

Yes, that is how I updated the package. I also updated them in my local machine just to be certain. I also updated cloudformation-cli-python-plugin in my machine to see if that would help, but unfortunately I had no luck with that either.

**Comment by ammokhov** [comment]
@ArnoldKell thanks for raising the issue. We will prioritize the fix

**Comment by maintux** [comment]
The same error here :(
Now our stack is blocked ...

**Comment by ArnoldKell** [comment]
The error seems to occur even when referring to attributes of the custom resource.

**Comment by yiuc** [comment]
We got same problem in CN region. Tried version 2.1.3

**Comment by ammokhov** [comment]
recently released [2.1.4](https://pypi.org/project/cloudformation-cli-python-lib/2.1.4/)
